[[redirects]]
  from = "/about"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/the-report"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/fact-sheet"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/media"
  to = "/"
  status = 200
  force = true

[context.jm-edits]
command = "npm run build && cp _nzap_headers build/_headers"
